rbac:
  create: false

image:
  tag: 1.8.11-debug
  
config:
  outputs: |
    [INPUT]
        Name tail
        Path /var/log/containers/*.log
        multiline.parser docker, cri
        Tag kube.*
        Skip_Long_Lines On
        Buffer_Chunk_Size 512m
        Buffer_Max_Size 512m
        Mem_Buf_Limit   1g
        Ignore_Older 5m
        
        
    [OUTPUT]
        Name            es
        Match           kube.*
        Host            elasticsearch-master
        Index           fluent-bit
        Logstash_Format Off
        Generate_ID     On
        Trace_Error     On
        Replace_Dots    On
        Buffer_Size     False
        Retry_Limit     1