rbac:
  create: false

image:
  tag: 1.8.11-debug
  
config:
  outputs: |
    [OUTPUT]
        Name            es
        Match           kube.*
        Host            elasticsearch-master
        Index           test
        Generate_ID     On
        Trace_Error     On
        Replace_Dots    On